
name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build . -t abel254/landing-page
    - run: echo "${{secrets.DOCTER_PASSWORD}}" | docker login -u ${{secrets.DOCTERHUB_USERNAME}} --password stdin
    - run: docker push abel254/landing-page